Add settings Dialog
realchrisward/Physiology-Analysis-Tools pull request #27
Opened 2024-09-30 15:33 UTC by e-selkirk

Adds a settings dialog for the settings used in Heart Beat detection and Arrhythmia detection

2024-10-02 15:06 UTC, realchrisward requested changes
just recommend renaming the class to better match the use case
SettingsWindow vs SubWindow

2024-10-02 15:06 UTC, realchrisward commented on src/physiology_analysis_tools/main.py
> +class SubWindow(QtWidgets.QDialog):
as the software continues to grow in complexity there may be more windows to address different aspects of the software. recommend changing name of this class to be more specific since it is a subwindow for addressing settings. 
'class SettingsWindow(QtWidgets.QDialog):

2024-10-02 15:06 UTC, realchrisward commented on src/physiology_analysis_tools/main.py
> +        window = SubWindow(parent = self)
recommended revision to class name would require change here as well for congruency
'window = SettingsWindow(parent = self)

2024-10-07 15:17 UTC, e-selkirk commented on src/physiology_analysis_tools/main.py
> +class SubWindow(QtWidgets.QDialog):
Fixed by #30

2024-10-07 15:17 UTC, e-selkirk commented on src/physiology_analysis_tools/main.py
> +        window = SubWindow(parent = self)
Fixed by #30

2024-10-07 16:56 UTC, realchrisward approved these changes
this appears to include the requested changes and additional improvements for more flexible settings as well

2024-10-07 17:00 UTC, merged